export const SET_MEETING_SCREEN = 'SET_MEETING_SCREEN';
export const MEETING_SCREEN = 'MEETING_SCREEN';

export const CHAT_SCREEN = 'CHAT_SCREEN';

export const DRAWER = 'DRAWER';

export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REG_SCREEN = 'REG_SCREEN';

export const MAIN_STACK = 'MAIN_STACK';
export const AUTHENTICATION_STACK = 'AUTHENTICATION_STACK';